// <auto-generated />
using System;
using LMS.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721171349_InstructorModuleInitial")]
    partial class InstructorModuleInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorAddress", b =>
                {
                    b.Property<long>("InstructorAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorAddressId"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InstructorAddressId");

                    b.HasIndex("InstructorProfileId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("InstructorAddresses", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorApproval", b =>
                {
                    b.Property<long>("InstructorApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorApprovalId"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApprovedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("InstructorApprovalId");

                    b.HasIndex("ApprovalStatus");

                    b.HasIndex("InstructorProfileId")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.ToTable("InstructorApprovals", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorAvailability", b =>
                {
                    b.Property<long>("InstructorAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorAvailabilityId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("InstructorAvailabilityId");

                    b.HasIndex("DayOfWeek");

                    b.HasIndex("InstructorProfileId")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.ToTable("InstructorAvailabilities", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorBankAccount", b =>
                {
                    b.Property<long>("InstructorBankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorBankAccountId"));

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SwiftCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("InstructorBankAccountId");

                    b.HasIndex("InstructorProfileId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsPrimary");

                    b.HasIndex("Verified");

                    b.ToTable("InstructorBankAccounts", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorCertification", b =>
                {
                    b.Property<long>("InstructorCertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorCertificationId"));

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CertificationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuingOrganization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("InstructorCertificationId");

                    b.HasIndex("CertificationName");

                    b.HasIndex("InstructorProfileId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("InstructorCertifications", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorDocument", b =>
                {
                    b.Property<long>("InstructorDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorDocumentId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("InstructorDocumentId");

                    b.HasIndex("DocumentType");

                    b.HasIndex("InstructorProfileId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Verified");

                    b.ToTable("InstructorDocuments", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorExperience", b =>
                {
                    b.Property<long>("InstructorExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorExperienceId"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("InstructorExperienceId");

                    b.HasIndex("Company");

                    b.HasIndex("InstructorProfileId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("InstructorExperiences", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorNotificationPreference", b =>
                {
                    b.Property<long>("InstructorNotificationPreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorNotificationPreferenceId"));

                    b.Property<bool>("EmailNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PushNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("SmsNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("InstructorNotificationPreferenceId");

                    b.HasIndex("InstructorProfileId")
                        .IsUnique();

                    b.ToTable("InstructorNotificationPreferences", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorPreference", b =>
                {
                    b.Property<long>("InstructorPreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorPreferenceId"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InstructorPreferenceId");

                    b.HasIndex("InstructorProfileId")
                        .IsUnique();

                    b.ToTable("InstructorPreferences", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorProfile", b =>
                {
                    b.Property<long>("InstructorProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorProfileId"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BannerImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("InstructorNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("ProfessionalHeadline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TotalCourses")
                        .HasColumnType("int");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("int");

                    b.HasKey("InstructorProfileId");

                    b.HasIndex("InstructorNumber")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsPremium");

                    b.HasIndex("UserId");

                    b.ToTable("InstructorProfiles", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorQualification", b =>
                {
                    b.Property<long>("InstructorQualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorQualificationId"));

                    b.Property<string>("CertificateFile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CompletedYear")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("QualificationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("InstructorQualificationId");

                    b.HasIndex("CompletedYear");

                    b.HasIndex("InstructorProfileId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("InstructorQualifications", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorSettings", b =>
                {
                    b.Property<long>("InstructorSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorSettingsId"));

                    b.Property<bool>("AllowCourseReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowPublicProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ShowRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("InstructorSettingsId");

                    b.HasIndex("InstructorProfileId")
                        .IsUnique();

                    b.ToTable("InstructorSettings", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorSkill", b =>
                {
                    b.Property<long>("InstructorSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorSkillId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("int");

                    b.HasKey("InstructorSkillId");

                    b.HasIndex("InstructorProfileId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SkillName");

                    b.ToTable("InstructorSkills", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorSocialLink", b =>
                {
                    b.Property<long>("InstructorSocialLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorSocialLinkId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("InstructorSocialLinkId");

                    b.HasIndex("InstructorProfileId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Platform");

                    b.ToTable("InstructorSocialLinks", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorSubscription", b =>
                {
                    b.Property<long>("InstructorSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorSubscriptionId"));

                    b.Property<bool>("AutoRenew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InstructorSubscriptionId");

                    b.HasIndex("InstructorProfileId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("SubscriptionType");

                    b.ToTable("InstructorSubscriptions", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorTaxProfile", b =>
                {
                    b.Property<long>("InstructorTaxProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorTaxProfileId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaxStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InstructorTaxProfileId");

                    b.HasIndex("InstructorProfileId")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("TaxNumber");

                    b.HasIndex("TaxStatus");

                    b.ToTable("InstructorTaxProfiles", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorVerification", b =>
                {
                    b.Property<long>("InstructorVerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorVerificationId"));

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("InstructorVerificationId");

                    b.HasIndex("InstructorProfileId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("InstructorVerifications", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorWallet", b =>
                {
                    b.Property<long>("InstructorWalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstructorWalletId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("CurrentBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<long>("InstructorProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastPayoutDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PendingBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalWithdrawn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("InstructorWalletId");

                    b.HasIndex("InstructorProfileId")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.ToTable("InstructorWallets", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentAddress", b =>
                {
                    b.Property<long>("StudentAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentAddressId"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StateProvince")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("StudentProfileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentAddressId");

                    b.HasIndex("CountryId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsPrimary");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("StudentAddresses", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentDocument", b =>
                {
                    b.Property<long>("StudentDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentDocumentId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("StudentProfileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentDocumentId");

                    b.HasIndex("DocumentType");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsVerified");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("StudentDocuments", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentEmergencyContact", b =>
                {
                    b.Property<long>("StudentEmergencyContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentEmergencyContactId"));

                    b.Property<string>("AlternativePhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("StudentProfileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentEmergencyContactId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsPrimary");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("StudentEmergencyContacts", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentNotificationPreference", b =>
                {
                    b.Property<long>("StudentNotificationPreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentNotificationPreferenceId"));

                    b.Property<bool>("AssignmentReminders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("CertificateNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("CourseAnnouncements")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("InstructorMessages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("MarketingNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PaymentNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("QuizReminders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("StudentProfileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentNotificationPreferenceId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("StudentProfileId")
                        .IsUnique();

                    b.ToTable("StudentNotificationPreferences", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentPreference", b =>
                {
                    b.Property<long>("StudentPreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentPreferenceId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("EmailNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("MarketingEmails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("MarketingSms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("PushNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("SmsNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("StudentProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentPreferenceId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("StudentProfileId")
                        .IsUnique();

                    b.ToTable("StudentPreferences", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentProfile", b =>
                {
                    b.Property<long>("StudentProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentProfileId"));

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Occupation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PreferredLanguageId")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TimeZoneId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentProfileId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsPremium");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("StudentProfiles", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentSettings", b =>
                {
                    b.Property<long>("StudentSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentSettingsId"));

                    b.Property<bool>("AllowDirectMessages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowPublicProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ProfileVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("RememberLastLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ShowPhoneNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("StudentProfileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentSettingsId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("StudentProfileId")
                        .IsUnique();

                    b.ToTable("StudentSettings", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentSubscription", b =>
                {
                    b.Property<long>("StudentSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentSubscriptionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("AutoRenew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long?>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("StudentProfileId")
                        .HasColumnType("bigint");

                    b.Property<int>("SubscriptionPlanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentSubscriptionId");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PaymentId");

                    b.HasIndex("StudentProfileId")
                        .IsUnique();

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("StudentSubscriptions", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentWishlist", b =>
                {
                    b.Property<long>("StudentWishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentWishlistId"));

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("StudentProfileId")
                        .HasColumnType("bigint");

                    b.HasKey("StudentWishlistId");

                    b.HasIndex("CourseId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("StudentProfileId", "CourseId")
                        .IsUnique();

                    b.ToTable("StudentWishlists", (string)null);
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorAddress", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithMany("InstructorAddresses")
                        .HasForeignKey("InstructorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorApproval", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithOne("InstructorApproval")
                        .HasForeignKey("LMS.Domain.Entities.Instructors.InstructorApproval", "InstructorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorAvailability", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithOne("InstructorAvailability")
                        .HasForeignKey("LMS.Domain.Entities.Instructors.InstructorAvailability", "InstructorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorBankAccount", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithMany("InstructorBankAccounts")
                        .HasForeignKey("InstructorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorCertification", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithMany("InstructorCertifications")
                        .HasForeignKey("InstructorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorDocument", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithMany("InstructorDocuments")
                        .HasForeignKey("InstructorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorExperience", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithMany("InstructorExperiences")
                        .HasForeignKey("InstructorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorNotificationPreference", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithOne("InstructorNotificationPreference")
                        .HasForeignKey("LMS.Domain.Entities.Instructors.InstructorNotificationPreference", "InstructorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorPreference", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithOne("InstructorPreference")
                        .HasForeignKey("LMS.Domain.Entities.Instructors.InstructorPreference", "InstructorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorQualification", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithMany("InstructorQualifications")
                        .HasForeignKey("InstructorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorSettings", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithOne("InstructorSettings")
                        .HasForeignKey("LMS.Domain.Entities.Instructors.InstructorSettings", "InstructorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorSkill", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithMany("InstructorSkills")
                        .HasForeignKey("InstructorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorSocialLink", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithMany("InstructorSocialLinks")
                        .HasForeignKey("InstructorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorSubscription", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithOne("InstructorSubscription")
                        .HasForeignKey("LMS.Domain.Entities.Instructors.InstructorSubscription", "InstructorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorTaxProfile", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithOne("InstructorTaxProfile")
                        .HasForeignKey("LMS.Domain.Entities.Instructors.InstructorTaxProfile", "InstructorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorVerification", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithOne("InstructorVerification")
                        .HasForeignKey("LMS.Domain.Entities.Instructors.InstructorVerification", "InstructorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorWallet", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Instructors.InstructorProfile", "InstructorProfile")
                        .WithOne("InstructorWallet")
                        .HasForeignKey("LMS.Domain.Entities.Instructors.InstructorWallet", "InstructorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstructorProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentAddress", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Students.StudentProfile", "StudentProfile")
                        .WithMany("StudentAddresses")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentDocument", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Students.StudentProfile", "StudentProfile")
                        .WithMany("StudentDocuments")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentEmergencyContact", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Students.StudentProfile", "StudentProfile")
                        .WithMany("StudentEmergencyContacts")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentNotificationPreference", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Students.StudentProfile", "StudentProfile")
                        .WithOne("StudentNotificationPreference")
                        .HasForeignKey("LMS.Domain.Entities.Students.StudentNotificationPreference", "StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentPreference", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Students.StudentProfile", "StudentProfile")
                        .WithOne("StudentPreference")
                        .HasForeignKey("LMS.Domain.Entities.Students.StudentPreference", "StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentSettings", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Students.StudentProfile", "StudentProfile")
                        .WithOne("StudentSettings")
                        .HasForeignKey("LMS.Domain.Entities.Students.StudentSettings", "StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentSubscription", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Students.StudentProfile", "StudentProfile")
                        .WithOne("StudentSubscription")
                        .HasForeignKey("LMS.Domain.Entities.Students.StudentSubscription", "StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentWishlist", b =>
                {
                    b.HasOne("LMS.Domain.Entities.Students.StudentProfile", "StudentProfile")
                        .WithMany("StudentWishlists")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Instructors.InstructorProfile", b =>
                {
                    b.Navigation("InstructorAddresses");

                    b.Navigation("InstructorApproval");

                    b.Navigation("InstructorAvailability");

                    b.Navigation("InstructorBankAccounts");

                    b.Navigation("InstructorCertifications");

                    b.Navigation("InstructorDocuments");

                    b.Navigation("InstructorExperiences");

                    b.Navigation("InstructorNotificationPreference");

                    b.Navigation("InstructorPreference");

                    b.Navigation("InstructorQualifications");

                    b.Navigation("InstructorSettings");

                    b.Navigation("InstructorSkills");

                    b.Navigation("InstructorSocialLinks");

                    b.Navigation("InstructorSubscription");

                    b.Navigation("InstructorTaxProfile");

                    b.Navigation("InstructorVerification");

                    b.Navigation("InstructorWallet");
                });

            modelBuilder.Entity("LMS.Domain.Entities.Students.StudentProfile", b =>
                {
                    b.Navigation("StudentAddresses");

                    b.Navigation("StudentDocuments");

                    b.Navigation("StudentEmergencyContacts");

                    b.Navigation("StudentNotificationPreference");

                    b.Navigation("StudentPreference");

                    b.Navigation("StudentSettings");

                    b.Navigation("StudentSubscription");

                    b.Navigation("StudentWishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
